/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  MoneyBoxesFactoryAbi,
  MoneyBoxesFactoryAbiInterface,
} from "../MoneyBoxesFactoryAbi";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "moneyBox",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "MoneyBoxesCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_safeAddress",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "percentage",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "bool",
            name: "isActive",
            type: "bool",
          },
        ],
        internalType: "struct MoneyBoxesModule.MoneyBoxConfiguration[]",
        name: "_boxesConfiguration",
        type: "tuple[]",
      },
    ],
    name: "createMoneyBoxesContract",
    outputs: [
      {
        internalType: "contract MoneyBoxesModule",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "getUserLatestMoneyBox",
    outputs: [
      {
        internalType: "contract MoneyBoxesModule",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "moneyBoxes",
    outputs: [
      {
        internalType: "contract MoneyBoxesModule",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class MoneyBoxesFactoryAbi__factory {
  static readonly abi = _abi;
  static createInterface(): MoneyBoxesFactoryAbiInterface {
    return new utils.Interface(_abi) as MoneyBoxesFactoryAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MoneyBoxesFactoryAbi {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MoneyBoxesFactoryAbi;
  }
}
